/**
 * =====================================================
 * DOCUMENT APPROVAL API
 * Approve/reject tenant documents & log to immutable ledger
 * =====================================================
 */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

export async function POST(request: NextRequest) {
  try {
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    // Get user from auth
    const authHeader = request.headers.get('authorization');
    if (!authHeader) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { documentId, action, rejectionReason } = await request.json();

    if (!documentId || !action) {
      return NextResponse.json(
        { error: 'documentId and action are required' },
        { status: 400 }
      );
    }

    if (!['approve', 'reject'].includes(action)) {
      return NextResponse.json(
        { error: 'action must be either "approve" or "reject"' },
        { status: 400 }
      );
    }

    // Fetch document
    const { data: document, error: fetchError } = await supabase
      .from('tenant_documents')
      .select('*')
      .eq('id', documentId)
      .single();

    if (fetchError || !document) {
      return NextResponse.json({ error: 'Document not found' }, { status: 404 });
    }

    // Update document status
    const newStatus = action === 'approve' ? 'APPROVED' : 'REJECTED';
    const { error: updateError } = await supabase
      .from('tenant_documents')
      .update({
        status: newStatus,
        reviewed_at: new Date().toISOString(),
        reviewed_by: 'current-user-id', // TODO: Get from auth
        rejection_reason: action === 'reject' ? rejectionReason : null,
      })
      .eq('id', documentId);

    if (updateError) {
      return NextResponse.json(
        { error: 'Failed to update document: ' + updateError.message },
        { status: 500 }
      );
    }

    // THE SHIELD: Log to immutable ledger if APPROVED
    if (action === 'approve' && document.document_type === 'INCOME_VERIFICATION') {
      const today = new Date();
      const { error: ledgerError } = await supabase
        .from('hud_append_ledger')
        .insert({
          organization_id: document.organization_id,
          property_id: document.property_id,
          unit_id: document.unit_id,
          tenant_id: document.tenant_id,
          transaction_type: 'INCOME_APPROVED',
          amount: 0.0,
          description: `Income Verification Approved. Document Type: ${document.document_type}. Document Hash: ${document.id}. File: ${document.file_name}`,
          accounting_period: `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}`,
          cryptographic_hash: '', // Auto-generated by trigger
          created_by: 'current-user-id', // TODO: Get from auth
        });

      if (ledgerError) {
        console.error('Ledger logging error:', ledgerError);
        // Don't fail the request, just log the error
      }
    }

    return NextResponse.json({
      success: true,
      message: `Document ${action}d successfully${action === 'approve' && document.document_type === 'INCOME_VERIFICATION' ? ' and logged to immutable ledger' : ''}`,
      document: {
        id: documentId,
        status: newStatus,
        reviewed_at: new Date().toISOString(),
      },
    });
  } catch (error) {
    console.error('Document approval error:', error);
    return NextResponse.json(
      {
        error: 'Internal server error',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
