/**
 * =====================================================
 * IMMUTABLE LEDGER VIEW & EXPORT
 * Financial-style ledger with CSV export for HUD auditors
 * Includes "Post Adjustment" for offsetting entries
 * =====================================================
 */

'use client';

import { useEffect, useState } from 'react';
import { useSystemState } from '@/hooks/useSystemState';
import { Card } from '@/components/ui/AnimatedCard';
import { createClient } from '@supabase/supabase-js';
import Papa from 'papaparse';

interface LedgerEntry {
  id: string;
  property_id: string;
  unit_id: string;
  tenant_id: string | null;
  transaction_type: string;
  amount: number;
  description: string;
  accounting_period: string;
  is_period_closed: boolean;
  cryptographic_hash: string;
  created_at: string;
  created_by: string;
}

export default function LedgerPage() {
  const { organization } = useSystemState();
  const [entries, setEntries] = useState<LedgerEntry[]>([]);
  const [filteredEntries, setFilteredEntries] = useState<LedgerEntry[]>([]);
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [showAdjustmentModal, setShowAdjustmentModal] = useState(false);
  const [adjustment, setAdjustment] = useState({
    property_id: '',
    unit_id: '',
    amount: 0,
    description: '',
    reason: '',
  });

  useEffect(() => {
    if (organization?.id) {
      fetchLedger();
    }
  }, [organization]);

  useEffect(() => {
    filterEntries();
  }, [entries, startDate, endDate]);

  async function fetchLedger() {
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
    );

    const { data } = await supabase
      .from('hud_append_ledger')
      .select('*')
      .eq('organization_id', organization!.id)
      .order('created_at', { ascending: false });

    if (data) setEntries(data);
  }

  function filterEntries() {
    let filtered = [...entries];

    if (startDate) {
      filtered = filtered.filter((e) => new Date(e.created_at) >= new Date(startDate));
    }

    if (endDate) {
      filtered = filtered.filter((e) => new Date(e.created_at) <= new Date(endDate));
    }

    setFilteredEntries(filtered);
  }

  async function handlePostAdjustment(e: React.FormEvent) {
    e.preventDefault();

    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
    );

    const today = new Date();
    const { error } = await supabase.from('hud_append_ledger').insert({
      organization_id: organization!.id,
      property_id: adjustment.property_id,
      unit_id: adjustment.unit_id,
      tenant_id: null,
      transaction_type: 'ADJUSTMENT',
      amount: adjustment.amount,
      description: `ADJUSTMENT: ${adjustment.description}. Reason: ${adjustment.reason}`,
      accounting_period: `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}`,
      cryptographic_hash: '', // Auto-generated by trigger
      created_by: 'current-user-id', // TODO: Replace with actual user
    });

    if (!error) {
      alert('✓ Adjustment posted to immutable ledger');
      setShowAdjustmentModal(false);
      setAdjustment({ property_id: '', unit_id: '', amount: 0, description: '', reason: '' });
      fetchLedger();
    } else {
      alert('Error: ' + error.message);
    }
  }

  function handleExportCSV() {
    const csvData = filteredEntries.map((entry) => ({
      Timestamp: new Date(entry.created_at).toLocaleString(),
      'Property ID': entry.property_id,
      'Unit ID': entry.unit_id,
      'Tenant ID': entry.tenant_id || 'N/A',
      'Transaction Type': entry.transaction_type,
      Amount: entry.amount.toFixed(2),
      Description: entry.description,
      'Accounting Period': entry.accounting_period,
      'Period Closed': entry.is_period_closed ? 'YES' : 'NO',
      'Cryptographic Hash': entry.cryptographic_hash,
    }));

    const csv = Papa.unparse(csvData);

    // Add header and footer
    const header = `# Generated by Wolf Shield HUD-Compliance Engine\n# Date: ${new Date().toLocaleString()}\n# Organization: ${organization?.name}\n# Cryptographic hashes verify this data has not been altered since the timestamp.\n\n`;
    const footer = `\n\n# End of Report\n# Total Entries: ${filteredEntries.length}\n# This ledger is mathematically tamper-proof and compliant with HUD auditing standards.`;

    const fullCSV = header + csv + footer;

    // Download
    const blob = new Blob([fullCSV], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `wolf-shield-ledger-${new Date().getTime()}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-8">
      <div className="mx-auto max-w-7xl">
        <div className="mb-8 flex items-center justify-between">
          <div>
            <h1 className="text-4xl font-bold text-emerald-400">📊 Immutable Ledger</h1>
            <p className="mt-2 text-slate-300">{entries.length} Total Entries</p>
          </div>
          <div className="flex gap-3">
            <button
              onClick={() => setShowAdjustmentModal(true)}
              className="rounded-lg border-2 border-yellow-500 px-6 py-3 font-bold text-yellow-400 transition hover:bg-yellow-500/10"
            >
              Post Adjustment
            </button>
            <button
              onClick={handleExportCSV}
              className="rounded-lg bg-emerald-500 px-6 py-3 font-bold text-white transition hover:bg-emerald-600"
            >
              Export for Auditor (CSV)
            </button>
          </div>
        </div>

        {/* Date Filter */}
        <Card className="mb-6 border-emerald-500/20 bg-slate-800/50 p-6 backdrop-blur">
          <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
            <div>
              <label className="mb-2 block text-sm font-bold text-slate-300">Start Date</label>
              <input
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                className="w-full rounded border border-slate-600 bg-slate-900 px-4 py-2 text-white focus:border-emerald-500 focus:outline-none"
              />
            </div>
            <div>
              <label className="mb-2 block text-sm font-bold text-slate-300">End Date</label>
              <input
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                className="w-full rounded border border-slate-600 bg-slate-900 px-4 py-2 text-white focus:border-emerald-500 focus:outline-none"
              />
            </div>
            <div className="flex items-end">
              <button
                onClick={() => {
                  setStartDate('');
                  setEndDate('');
                }}
                className="w-full rounded bg-slate-700 px-4 py-2 font-bold text-white transition hover:bg-slate-600"
              >
                Clear Filters
              </button>
            </div>
          </div>
          <div className="mt-4 text-sm text-slate-400">
            Showing {filteredEntries.length} of {entries.length} entries
          </div>
        </Card>

        {/* Ledger Table - Financial Style */}
        <Card className="border-emerald-500/20 bg-slate-800/50 backdrop-blur">
          <div className="overflow-x-auto">
            <table className="w-full border-collapse text-sm">
              <thead className="border-b-2 border-emerald-500 bg-slate-900/50">
                <tr>
                  <th className="px-4 py-3 text-left font-mono text-xs uppercase text-slate-400">Timestamp</th>
                  <th className="px-4 py-3 text-left font-mono text-xs uppercase text-slate-400">Type</th>
                  <th className="px-4 py-3 text-right font-mono text-xs uppercase text-slate-400">Amount</th>
                  <th className="px-4 py-3 text-left font-mono text-xs uppercase text-slate-400">Description</th>
                  <th className="px-4 py-3 text-center font-mono text-xs uppercase text-slate-400">Period</th>
                  <th className="px-4 py-3 text-left font-mono text-xs uppercase text-slate-400">Hash</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-700">
                {filteredEntries.map((entry) => (
                  <tr key={entry.id} className="hover:bg-slate-700/30">
                    <td className="px-4 py-3 font-mono text-xs text-slate-300">
                      {new Date(entry.created_at).toLocaleString()}
                    </td>
                    <td className="px-4 py-3">
                      <span className={`rounded px-2 py-1 text-xs font-bold ${
                        entry.transaction_type === 'PAYMENT' || entry.transaction_type === 'CHARGE'
                          ? 'bg-emerald-500/20 text-emerald-400'
                          : entry.transaction_type === 'ADJUSTMENT'
                          ? 'bg-yellow-500/20 text-yellow-400'
                          : 'bg-blue-500/20 text-blue-400'
                      }`}>
                        {entry.transaction_type}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-right font-mono text-emerald-400">
                      ${entry.amount.toFixed(2)}
                    </td>
                    <td className="px-4 py-3 text-slate-300">{entry.description.substring(0, 80)}{entry.description.length > 80 ? '...' : ''}</td>
                    <td className="px-4 py-3 text-center">
                      <span className={`rounded px-2 py-1 text-xs ${
                        entry.is_period_closed ? 'bg-red-500/20 text-red-400' : 'bg-green-500/20 text-green-400'
                      }`}>
                        {entry.accounting_period}
                        {entry.is_period_closed && ' 🔒'}
                      </span>
                    </td>
                    <td className="px-4 py-3 font-mono text-xs text-slate-500">
                      0x{entry.cryptographic_hash.substring(0, 8)}...
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            {filteredEntries.length === 0 && (
              <div className="py-12 text-center text-slate-400">
                No ledger entries found for the selected date range
              </div>
            )}
          </div>
        </Card>

        {/* Adjustment Modal */}
        {showAdjustmentModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4">
            <Card className="w-full max-w-2xl border-yellow-500/20 bg-slate-800 p-8">
              <h2 className="mb-2 text-2xl font-bold text-yellow-400">Post Offsetting Adjustment</h2>
              <p className="mb-6 text-sm text-slate-400">
                The ledger is immutable. To correct an error, post a new offsetting transaction.
              </p>

              <form onSubmit={handlePostAdjustment} className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="mb-2 block text-sm font-bold text-slate-300">Property ID *</label>
                    <input
                      type="text"
                      required
                      value={adjustment.property_id}
                      onChange={(e) => setAdjustment({ ...adjustment, property_id: e.target.value })}
                      className="w-full rounded border border-slate-600 bg-slate-900 px-4 py-2 text-white focus:border-emerald-500 focus:outline-none"
                      placeholder="UUID"
                    />
                  </div>
                  <div>
                    <label className="mb-2 block text-sm font-bold text-slate-300">Unit ID *</label>
                    <input
                      type="text"
                      required
                      value={adjustment.unit_id}
                      onChange={(e) => setAdjustment({ ...adjustment, unit_id: e.target.value })}
                      className="w-full rounded border border-slate-600 bg-slate-900 px-4 py-2 text-white focus:border-emerald-500 focus:outline-none"
                      placeholder="UUID"
                    />
                  </div>
                </div>

                <div>
                  <label className="mb-2 block text-sm font-bold text-slate-300">Adjustment Amount *</label>
                  <input
                    type="number"
                    required
                    step="0.01"
                    value={adjustment.amount}
                    onChange={(e) => setAdjustment({ ...adjustment, amount: parseFloat(e.target.value) })}
                    className="w-full rounded border border-slate-600 bg-slate-900 px-4 py-2 text-white focus:border-emerald-500 focus:outline-none"
                    placeholder="Use negative for credits (e.g., -450.00)"
                  />
                  <p className="mt-1 text-xs text-slate-400">
                    Example: If you charged $500 instead of $50, post -$450.00
                  </p>
                </div>

                <div>
                  <label className="mb-2 block text-sm font-bold text-slate-300">Description *</label>
                  <input
                    type="text"
                    required
                    value={adjustment.description}
                    onChange={(e) => setAdjustment({ ...adjustment, description: e.target.value })}
                    className="w-full rounded border border-slate-600 bg-slate-900 px-4 py-2 text-white focus:border-emerald-500 focus:outline-none"
                    placeholder="Correcting charge error"
                  />
                </div>

                <div>
                  <label className="mb-2 block text-sm font-bold text-slate-300">Reason for Adjustment *</label>
                  <textarea
                    required
                    value={adjustment.reason}
                    onChange={(e) => setAdjustment({ ...adjustment, reason: e.target.value })}
                    className="h-24 w-full rounded border border-slate-600 bg-slate-900 px-4 py-2 text-white focus:border-emerald-500 focus:outline-none"
                    placeholder="Explain why this adjustment is necessary..."
                  />
                </div>

                <div className="flex gap-4 pt-4">
                  <button
                    type="submit"
                    className="flex-1 rounded-lg bg-yellow-500 px-6 py-3 font-bold text-white transition hover:bg-yellow-600"
                  >
                    Post Adjustment to Ledger
                  </button>
                  <button
                    type="button"
                    onClick={() => setShowAdjustmentModal(false)}
                    className="flex-1 rounded-lg border-2 border-slate-600 px-6 py-3 font-bold text-slate-300 transition hover:bg-slate-700"
                  >
                    Cancel
                  </button>
                </div>
              </form>
            </Card>
          </div>
        )}
      </div>
    </div>
  );
}
