/**
 * =====================================================
 * RECERTIFICATION WIDGET
 * Color-coded 90-60-30 day HUD alerts
 * =====================================================
 */

'use client';

import { useEffect, useState } from 'react';
import { createClient } from '@supabase/supabase-js';
import { Card } from '@/components/ui/AnimatedCard';

interface Alert {
  id: string;
  alert_type: string;
  message: string;
  unit_id: string;
  tenant_id: string;
  property_id: string;
  created_at: string;
  metadata: any;
}

export function RecertificationWidget({ organizationId }: { organizationId: string }) {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAlerts();
  }, [organizationId]);

  async function fetchAlerts() {
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
    );

    const { data, error } = await supabase
      .from('compliance_alerts')
      .select('*')
      .eq('organization_id', organizationId)
      .in('alert_type', ['90_DAY', '60_DAY', '30_DAY', 'OVERDUE'])
      .eq('is_resolved', false)
      .order('created_at', { ascending: false })
      .limit(10);

    if (!error && data) {
      setAlerts(data);
    }
    setLoading(false);
  }

  async function handleSendReminder(alert: Alert) {
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
    );

    // Log reminder to ledger
    const today = new Date();
    await supabase.from('hud_append_ledger').insert({
      organization_id: organizationId,
      property_id: alert.property_id,
      unit_id: alert.unit_id,
      tenant_id: alert.tenant_id,
      transaction_type: 'NOTICE_GENERATED',
      amount: 0.0,
      description: `Manual recertification reminder sent. Alert type: ${alert.alert_type}`,
      accounting_period: `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}`,
      cryptographic_hash: '', // Auto-generated by trigger
      created_by: 'current-user-id', // TODO: Replace with actual user ID from auth
    });

    alert('✓ Reminder sent and logged to immutable ledger');
    fetchAlerts(); // Refresh
  }

  const getAlertColor = (type: string) => {
    if (type === 'OVERDUE' || type === '30_DAY') return 'border-red-500/50 bg-red-900/20';
    if (type === '60_DAY') return 'border-yellow-500/50 bg-yellow-900/20';
    return 'border-blue-500/50 bg-blue-900/20';
  };

  const getAlertLabel = (type: string) => {
    if (type === 'OVERDUE') return '🚨 OVERDUE';
    if (type === '30_DAY') return '🔴 30-Day Notice';
    if (type === '60_DAY') return '🟡 60-Day Notice';
    return '🔵 90-Day Notice';
  };

  const getAlertTextColor = (type: string) => {
    if (type === 'OVERDUE' || type === '30_DAY') return 'text-red-400';
    if (type === '60_DAY') return 'text-yellow-400';
    return 'text-blue-400';
  };

  if (loading) {
    return (
      <Card className="border-emerald-500/20 bg-slate-800/50 p-6 backdrop-blur">
        <h2 className="mb-4 text-xl font-bold text-emerald-400">Recertification Alerts</h2>
        <div className="text-center text-sm text-slate-400">Loading alerts...</div>
      </Card>
    );
  }

  return (
    <Card className="border-emerald-500/20 bg-slate-800/50 p-6 backdrop-blur">
      <h2 className="mb-4 text-xl font-bold text-emerald-400">📋 Recertification Alerts</h2>

      {alerts.length === 0 ? (
        <div className="rounded bg-slate-900/50 p-4 text-center text-sm text-slate-400">
          ✓ No pending recertifications. All tenants up to date.
        </div>
      ) : (
        <div className="space-y-3">
          {alerts.map((alert) => (
            <div key={alert.id} className={`rounded border p-3 ${getAlertColor(alert.alert_type)}`}>
              <div className="mb-2 flex items-start justify-between">
                <div className="flex-1">
                  <span className={`text-xs font-bold ${getAlertTextColor(alert.alert_type)}`}>
                    {getAlertLabel(alert.alert_type)}
                  </span>
                  <p className="mt-1 text-sm text-slate-300">{alert.message}</p>
                  <p className="mt-1 text-xs text-slate-500">
                    Created: {new Date(alert.created_at).toLocaleDateString()}
                  </p>
                </div>
              </div>
              <button
                onClick={() => handleSendReminder(alert)}
                className="mt-2 rounded bg-emerald-500 px-3 py-1 text-xs font-bold text-white transition hover:bg-emerald-600"
              >
                Send Tenant Reminder
              </button>
            </div>
          ))}
        </div>
      )}

      {alerts.length > 0 && (
        <div className="mt-4 text-center">
          <a href="/dashboard/property-manager/compliance" className="text-sm text-emerald-400 hover:underline">
            View All Alerts →
          </a>
        </div>
      )}
    </Card>
  );
}
