/**
 * =====================================================
 * RECERTIFICATION CRON JOB
 * Runs daily at 8:00 AM UTC via Vercel Cron
 * Generates 90-60-30 day alerts for tenant recertifications
 * =====================================================
 */

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

export async function GET(request: NextRequest) {
  try {
    // Security: Verify cron secret
    const authHeader = request.headers.get('authorization');
    if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    const today = new Date();
    const alerts_created: string[] = [];
    const ledger_entries: string[] = [];

    // Calculate target dates for 90, 60, 30 days from now
    const date90 = new Date(today);
    date90.setDate(today.getDate() + 90);
    
    const date60 = new Date(today);
    date60.setDate(today.getDate() + 60);
    
    const date30 = new Date(today);
    date30.setDate(today.getDate() + 30);

    // Fetch ACTIVE leases where next_recertification_due matches alert thresholds
    const { data: leases, error: leasesError } = await supabase
      .from('leases')
      .select('*')
      .eq('status', 'ACTIVE')
      .in('recertification_status', ['UP_TO_DATE', 'DUE_90', 'DUE_60']);

    if (leasesError) throw leasesError;

    for (const lease of leases || []) {
      const recertDue = new Date(lease.next_recertification_due);
      const daysUntil = Math.ceil((recertDue.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));

      let alertType: string | null = null;
      let newStatus: string | null = null;

      // Check if this lease hits an alert threshold TODAY
      if (daysUntil === 90 && lease.recertification_status === 'UP_TO_DATE') {
        alertType = '90_DAY';
        newStatus = 'DUE_90';
      } else if (daysUntil === 60 && lease.recertification_status === 'DUE_90') {
        alertType = '60_DAY';
        newStatus = 'DUE_60';
      } else if (daysUntil === 30 && lease.recertification_status === 'DUE_60') {
        alertType = '30_DAY';
        newStatus = 'DUE_30';
      } else if (daysUntil <= 0 && lease.recertification_status !== 'OVERDUE') {
        alertType = 'OVERDUE';
        newStatus = 'OVERDUE';
      }

      if (alertType && newStatus) {
        // 1. Update lease recertification_status
        await supabase
          .from('leases')
          .update({ recertification_status: newStatus })
          .eq('id', lease.id);

        // 2. Create compliance alert
        const { data: alert, error: alertError } = await supabase
          .from('compliance_alerts')
          .insert({
            organization_id: lease.organization_id,
            property_id: lease.property_id,
            unit_id: lease.unit_id,
            tenant_id: lease.tenant_id,
            lease_id: lease.id,
            alert_type: alertType,
            priority: alertType === 'OVERDUE' || alertType === '30_DAY' ? 'HIGH' : 'MEDIUM',
            message: `Tenant recertification ${alertType.replace('_', ' ')} notice for Unit ID: ${lease.unit_id}`,
            metadata: { lease_end_date: lease.end_date, days_until: daysUntil },
          })
          .select()
          .single();

        if (alertError) {
          console.error('Error creating alert:', alertError);
          continue;
        }

        alerts_created.push(alert.id);

        // 3. Log to hud_append_ledger (HUD requires proof of notice)
        const { data: ledgerEntry, error: ledgerError } = await supabase
          .from('hud_append_ledger')
          .insert({
            organization_id: lease.organization_id,
            property_id: lease.property_id,
            unit_id: lease.unit_id,
            tenant_id: lease.tenant_id,
            transaction_type: 'NOTICE_GENERATED',
            amount: 0.00,
            description: `Recertification ${alertType.replace('_', ' ')} notice generated automatically. Lease end: ${new Date(lease.end_date).toLocaleDateString()}`,
            accounting_period: `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}`,
            cryptographic_hash: '', // Will be auto-generated by trigger
            created_by: '00000000-0000-0000-0000-000000000000', // System user
          })
          .select()
          .single();

        if (ledgerError) {
          console.error('Error creating ledger entry:', ledgerError);
          continue;
        }

        ledger_entries.push(ledgerEntry.id);
      }
    }

    return NextResponse.json({
      success: true,
      message: 'Recertification alerts processed',
      stats: {
        leases_checked: leases?.length || 0,
        alerts_created: alerts_created.length,
        ledger_entries: ledger_entries.length,
      },
      alerts_created,
      ledger_entries,
    });
  } catch (error) {
    console.error('Cron job error:', error);
    return NextResponse.json(
      {
        error: 'Internal server error',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
